version: '3'

services:

  php:
    build:
        context: ../
        dockerfile: ./docker/php/Dockerfile
    container_name: "php"
    ports:
    - "8000:8000"
    depends_on:
    - db
    volumes:
    - ../:/var/www/
    - ./php.ini:/usr/local/etc/php/php.ini
    entrypoint:
    - /var/www/docker/script.sh
    hostname: php
  db:
    image: mysql:5.7
    volumes:
    - ./mysql:/var/lib/mysql
    ports:
    - "3306:3306"
    container_name: "mysql"
    environment:
    - MYSQL_DATABASE=ScrumBattle
    - MYSQL_USER=ScrumBattle
    - MYSQL_PASSWORD=ScrumBattle
    - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
    - db
    ports:
    - "8081:80"
networks:
  default:
    driver: bridge
