version: '3'

services:
  web_server:
    image: nginx:latest
    ports:
    - "8000:80"
    depends_on:
    - php
    volumes:
    - ../:/var/www/
    - ./sites-enabled:/etc/nginx/sites-enabled
    - ./nginx.conf:/etc/nginx/nginx.conf
    links:
    - php


  php:
    build:
        context: ../
        dockerfile: ./docker/php/Dockerfile
    container_name: "php"
    depends_on:
    - db
    volumes:
    - ../:/var/www/
    - ./php.ini:/usr/local/etc/php/php.ini
    entrypoint:
    - /var/www/docker/script.sh

  db:
    image: mysql:5.7
    volumes:
    - ./mysql:/var/lib/mysql
    ports:
    - "3306:3306"
    container_name: "mysql"
    environment:
    - MYSQL_DATABASE=ScrumBattle
    - MYSQL_USER=ScrumBattle
    - MYSQL_PASSWORD=ScrumBattle
    - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
    - db
    ports:
    - "8081:80"
networks:
  default:
    driver: bridge
